on:
  push
jobs:
  ubuntu20-depends:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Update apt repos
        run: sudo apt-get update

      - name: Install base dependencies      
        run: sudo apt-get install build-essential xutils-dev libtool gperf autotools-dev automake pkg-config bsdmainutils libattr1-dev make automake bison byacc cmake curl g++-multilib binutils-gold bison byacc python3 libevent-dev libboost-all-dev

      - name: List current directory
        run: ls -R

      - name: execute permission for autogen.sh
        run: chmod +x autogen.sh
      
      - name: Auto generate
        run: ./autogen.sh

      - name: execute permission to configure script
        run: chmod +x configure

      - name: configure
        run: CONFIG_SITE=$PWD/depends/x86_64-linux-gnu/share/config.site ./configure --enable-gui --disable-bench --disable-tests --disable-dependency-tracking --disable-werror --prefix=`pwd`/depends/x86_64-linux-gnu

      - name: Build project
        run: make -j4
