on:
  push
jobs:
  ubuntu20-depends:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Update apt repos
        run: sudo add-apt-repository universe && sudo apt-get update
             
      - name: Install base dependencies      
        run: sudo apt-get install -y build-essential xutils-dev libtool gperf autotools-dev automake pkg-config bsdmainutils libattr1-dev make automake bison byacc cmake curl g++-multilib binutils-gold bison byacc python3 libevent-dev libboost-all-dev qtbase5-dev qttools5-dev-tools

      - name: Install dependencies for building Qt5
        run: sudo apt-get install -y libx11-dev libjpeg-dev libpng-dev libtiff-dev libwebp-dev libxslt-dev qtdeclarative5-dev qtpositioning5-dev qtbase5-private-dev qt5-qmake qt5-default libqt5sensors5-dev
      
    #  - name: Clone and build QtWebKit from source
    #    run: |
    #      git clone https://github.com/qt/qtwebkit.git
    #      cd qtwebkit
    #      git checkout 5.212  # Checkout the correct branch for Qt5
    #      mkdir build
    #      cd build
    #      cmake ..
    #      make -j$
    #      sudo make install

      - name: Clone and build QtSensors from source
        run: |
          git clone https://github.com/qt/qtsensors.git
          cd qtsensors
          git checkout 5.15  # Switch to a Qt5-compatible branch
          qmake CONFIG-=examples  # Exclude examples from the build
          make -j$(nproc) -C src
          sudo make install
      
      - name: List current directory
        run: ls -R

      - name: execute permission for autogen.sh
       # if: exists('./autogen.sh')  # Check if file exists
        run: chmod +x autogen.sh

      - name: run autogen.sh to generate configure script
        run: ./autogen.sh
            
      - name: execute permission to configure script
        run: chmod +x configure

      - name: configure
        run: |
          export CMAKE_PREFIX_PATH=/usr/local/lib/cmake/Qt5Sensors  # Adjust the path if needed
          CONFIG_SITE=$PWD/depends/x86_64-linux-gnu/share/config.site ./configure --enable-gui --disable-bench --disable-tests --disable-dependency-tracking --disable-werror --prefix=`pwd`/depends/x86_64-linux-gnu

      - name: Build project
        run: make -j$(nproc) V=1
